---
v1:
  oakley:
    type: "OodCluster::Cluster"
    data:
      servers:
        login:
          type: "OodCluster::Servers::Ssh"
          data:
            host: "oakley.osc.edu"
        resource_mgr:
          type: "OodCluster::Servers::Torque"
          data:
            host: "oak-batch.osc.edu"
            lib: "/opt/torque/lib64"
            bin: "/opt/torque/bin"
            version: "6.0.1"
        scheduler:
          type: "OodCluster::Servers::Moab"
          data:
            host: "oak-batch.osc.edu"
            bin: "/opt/moab/bin"
            version: "9.0.1"
            moabhomedir: "/var/spool/moab"
        ganglia:
          type: "OodCluster::Servers::Ganglia"
          data:
            host: "cts05.osc.edu"
            scheme: "https://"
            segments:
              - "gweb"
              - "graph.php"
            req_query:
              c: "Oakley nodes"
            opt_query:
              h: "%{h}.ten.osc.edu"
            version: "3"
  ruby:
    type: "OodCluster::Cluster"
    data:
      servers:
        login:
          type: "OodCluster::Servers::Ssh"
          data:
            host: "ruby.osc.edu"
        resource_mgr:
          type: "OodCluster::Servers::Torque"
          data:
            host: "ruby-batch.osc.edu"
            lib: "/opt/torque/lib64"
            bin: "/opt/torque/bin"
            version: "6.0.1"
        scheduler:
          type: "OodCluster::Servers::Moab"
          data:
            host: "ruby-batch.osc.edu"
            bin: "/opt/moab/bin"
            version: "9.0.1"
            moabhomedir: "/var/spool/moab"
        ganglia:
          type: "OodCluster::Servers::Ganglia"
          data:
            host: "cts05.osc.edu"
            scheme: "https://"
            segments:
              - "gweb"
              - "graph.php"
            req_query:
              c: "Ruby"
            opt_query:
              h: "%{h}.ten.osc.edu"
            version: "3"
  quick:
    type: "OodCluster::Cluster"
    data:
      hpc_cluster: false
      servers:
        resource_mgr:
          type: "OodCluster::Servers::Torque"
          data:
            host: "quick-batch.osc.edu"
            lib: "/opt/torque/lib64"
            bin: "/opt/torque/bin"
            version: "6.0.1"
            sub_cluster:
              - "ruby"
              - "oakley"
